version: "3.8"
services:
  postgres:
    image: "postgres:latest"
    container_name: "test_postgres"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    ports:
      - "5433:5432"
